site_name: Hospitalrun
site_url: https://Hospitalrun.io
site_description: Hospitalrun project documentation
site_author: Hospitalrun Core Team

repo_url: https://github.com/Hospitalrun/Hospitalrun-frontend/

theme:
  name: readthedocs
  highlightjs: true

plugins:
  - search
