site_name: NeuReg
site_url: https://NeuReg.io
site_description: NeuReg project documentation
site_author: NeuReg Core Team

repo_url: https://github.com/NeuReg/NeuReg-frontend/

theme:
  name: readthedocs
  highlightjs: true

plugins:
  - search
